### ISSUE TITLE
Eccentric_Tensioners missing the .stl fileextension in the stl BOM list

### ISSUE THREAD

**Issue by t0b4cc0** [TadPath/PUMA#10]
Hi! I am working on building a PUMA microscope. I am also working on a configurator that just prints out a BOM, stls, links etc with build lists.

I noticed that in the stl file list the 

FG_Eccentric_Tensioner_Top
FG_Eccentric_Tensioner_Bottom
FG_Eccentric_Tensioner_Pulley_c_adhesin

are missing the ".stl" file extension

As is like to keep this automated I wonder is that intentional and i have to work with it or just an oversight?

It seems like all things that are actual .stl files have the stl file extension. and the other things in this list are just headings grouping the items right?

EDIT: also AR_Clip_lock has no stl file ending. I can easily deal with this, i just wonder why this is the case.

**Comment by TadPath** [comment]
Hello. Thanks for pointing these out. You are correct, the lack of stl extension is simply an oversight on my part. I will fix this in the next commit for the sake of consistency. However, In the longer term future I am not sure if I should keep the stl extensions as some people prefer to work with 3mf files instead and, anyway, I don't provide actual stl files I provide FreeCAD models and people are free to choose what kind of print-ready format they generate from it. So maybe it would be better for the long term applicability of your program if you bear in mind that this extension could change or be omitted in future versions. I look forward to seeing your configurator in action!

**Comment by t0b4cc0** [comment]
Nice thank you. I just didnt know if there was something special to these objects. It works now without relying on the extension.

I will say that its a bit helpful atleast to have the extension to know that this is actually one file that is printable, and easy interchangable with whatever file extension I choose for a build.
