### ISSUE TITLE
Missing Files in Focus_Gears.FCStd

### ISSUE THREAD

**Issue by sssmc** [TadPath/PUMA#13]
I have been going through the process of exporting the FreeCAD models to STLs and I have run into some issues with Focus_Gears.FCStd I have only been able to find a few of the parts(fine_gear, pulley_coarse, Eccentric_Tensioner_Pulley) the rest seem to be missing from the file. However, I downloaded the previous version of the file(commit: 138bdff9b5af1c9289edc4f3a830379d797513e4 from Mar 21, 2021) and found all the models to be present in that version. Here is a screenshot of the tree view from the most recent version:
![tree_view_new](https://user-images.githubusercontent.com/12385051/152716758-71025cc9-362d-4a49-b059-1761808e9355.PNG)
And here is one from the older version:
![tree_view_old](https://user-images.githubusercontent.com/12385051/152716759-5f50ef60-0432-4495-9548-a3414eadac14.PNG)

Apologies if this is a simple fix, I'm using FreeCAD for the first time with this project.

**Comment by TadPath** [comment]
Hello. This appears to be an OS or FreeCAD version compatibility issue. I just downloaded the FocusGears file in response to your issue and opened it on FreeCAD v0.19 under linux and I found the tree view to be the same as the good one you showed.
What version of FreeCAD are you using and what OS? Can you load FreeCAD 0.19 and see a correct display?
Although unlikely it may just be a transmission error in the particular downlad you did so also perhaps try downloading the file again. Also, do other FreeCAD files show errors like this or is the FocusGears the only one you tried? Can you try one or two more to see if the same thing happens? Also, can you report what version of Python you have installed? (I believe FreeCAD uses python).
If any or none of the above works, let me know - I may have to raise the issue with the FreeCAD developers.

**Comment by sssmc** [comment]
Thanks for the timely reply. I used freeCAD version 0.18 on Windows 10 to take the above screenshots. Upgrading to 0.19 fixed the issue. Thanks again.
