### ISSUE TITLE
Update for URLs in BOM

### ISSUE THREAD

**Issue by UlfWetzker** [TadPath/PUMA#16]
I found a few parts in the Non_Printed_Parts sheet of the PUMA_Bill_of_Materials.xls whose URLs are no longer accurate.

Pages that no longer exist:
Row 116: Polarising film for polariser 0.7 mm thick
Row 117: Polarising film for analyser 0.13 mm thick

I have been looking for other polarizing films of this thickness. Unfortunately, I could not find anything through the search of Aliexpress. Is the thickness of the polarizing filters very important or can I take other thicknesses here? In general, there are many polarizing films on Aliexpress, but whether these can be used is questionable.

Products that are no longer available:
Row 111: Mirror_2cm_square_first_surface_full_2mm_thick
Row 114: Beamsplitter_glass_2cm_square_1.1mm_thick

The Bohroptics Aliexpress shop is apparently on vacation. Maybe the products will be available again soon.

If alternative sources for these parts are known, I would appreciate an update of the Excel file.

**Comment by TadPath** [comment]
Hello. Thanks for the heads up. I have updated the link to the polariser sheet examplar supplier - it seems they just switched address link for some reason. Regarding thickness - it must be <= 0.9 mm to fit in the filter trays for PUMA. For use with the DI_Uber_pol it must be as thin as possible - but the exact thickness is not crucial. I mentioned this in some new notes added to the BOM spreadsheet.
A quick search on AE found an alternative supplier of the 2 cm square first surface mirror here (but I am NOT recommending them - they are more expensive and I haven't tried them out - just saying if you shop around you should find these generic products across a number of stores - it may take some time and effort searching using the correct search key words, etc.): https://www.aliexpress.com/item/4000582254851.html
If any product proves to be unavailable in the long term I will just have to see if I can make a modified model to accept whatever is available but I think availability will fluctuate over time for any single item.
