### ISSUE TITLE
cannot dowload valid zip or clone the archive 

### ISSUE THREAD

**Issue by aryehw** [TadPath/PUMA#19]
**Describe the bug**
git clone https://github.com/TadPath/PUMA.git
fails near the end of the process - no clone is created
downloading the zip produces a 75MB file, but the archive cannot be opened by the archive manager of ubuntu

**To Reproduce**
Attempt tp clone or download zip as described above.

**Expected behavior**
a valid zip archive should be downloaded, or a clone of the main branch should be constructed.

**Desktop (please complete the following information):**
 - OS: pop os ubuntu 22.04
 - Browser: Firefox]
 - Version 101.0.1

**Additional context**
First attempt to download zip produced a 38MB file (that also was an invalid archive).

Thanks for any assistance.

**Comment by sssmc** [comment]
The zip I dowloaded via Edge was 132.8MB and the one I downloaded via wget on Ubuntu was 127MB. Looks like your download is cutting cut off for some reason. Have you tried a command like this: 
`wget https://github.com/TadPath/PUMA/archive/refs/heads/main.zip`

**Comment by aryehw** [comment]
It also failed with wget. 
It appears to be a problem with my network. I moved from wired to wireless, and managed on the second attempt to get a complete download of the zipped archive. It is 126.69 MB on my system.
Thank you for your assistance.
