### ISSUE TITLE
missing python module

### ISSUE THREAD

**Issue by tiarno** [TadPath/PUMA#20]
**Describe the bug**
When I load the file Focus_Gears into FreeCad 0.19, I get this traceback:
Note: This doesn't happen with the file Stage.FCStd, but does the same with Binocular.

09:43:43  Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'FastenersCmd'
09:43:43  Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'FastenersCmd'
09:43:46  Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'FastenersCmd'
09:43:46  Traceback (most recent call last):
  File "C:\Program Files\FreeCAD 0.19\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
<class 'ModuleNotFoundError'>: No module named 'FastenersCmd'

**To Reproduce**
1. Open FreeCad 0.19
2. Open file Focus_Gears.FCStd
3. See error

**Expected behavior**
No errors on loading file

**Desktop (please complete the following information):**
 - OS:  Windows 10

**Comment by TadPath** [comment]
Hello. Thanks for this. I forgot to mention that I use the Fasteners Workbench which is an addon to FreeCAD. So perhaps if you install this addon it might fix the problem. Here are the instructions: https://wiki.freecadweb.org/Fasteners_Workbench
Please let me know if that works.

**Comment by tiarno** [comment]
What a fast response, thanks! Yes, I installed the workbench and now I no longer get the missing module issue.
I appreciate your work, I'm printing my first item now.

**Comment by TadPath** [comment]
That's great. I've now edited the FreeCAD ReadMe in the main repo for others to avoid this issue. Hope it goes well.
