### ISSUE TITLE
[FEATURE REQUEST] Add contributing guidelines

### ISSUE THREAD

**Issue by darigovresearch** [TadPath/PUMA#7]
**Is your feature request related to a problem? Please describe.**
Have a contributing guide so that those people wishing to contribute know the best format to make contributions

**Describe the solution you'd like**
A specific contributing.md file or section in the readme

**Describe alternatives you've considered**
Specific documentation like read the docs or the like

**Additional context**
Suggestion comes from https://github.com/TadPath/PUMA/pull/2#pullrequestreview-738186990 and an MVP could be just noting in the readme that pull requests are welcome & UK/British English is used in the text

**Comment by TadPath** [comment]
I do have a 'CONTRIBUTING.md' in PUMA/docs but this could do with a bit more detail and fleshing out. I am working on it as an ongoing concern - but it does already exist in a basic form.
