### ISSUE TITLE
Collector_mirror_block clamping problem

### ISSUE THREAD

**Issue by DerFetzer** [TadPath/PUMA#9]
**Describe the bug**
The holes for the thumbscrews in the Collector_mirror_block are not going through the shell.
Is this a design choice and the screw is supposed to deform the shell for the clamping effect or are they missing?

**Expected behavior**
I expected holes like in M3_Adjustment_ring_Kohler.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/11207998/137172262-3708dbce-88bd-434f-8793-6809d503a3b0.png)

**Comment by TadPath** [comment]
Thank you for considering the project and asking the question.The answer is no, this is not a bug or issue. This is a design implementation as I will now explain. In both models the slot you see is to accept an M3 nut which furnishes the thread to drive the screw through to grip the articulating part (I assume you already got that). However, the two models do 'gripping' in different ways for different reasons. DI_M3_Adjustment_ring_Kohler passes the screw end directly onto the indented ring on the outer surface of the DI_LC_Adjust_collar and grips it that way - you need the little screw end to grip directly into this little channel to allow maximum angle adjustment with this small diameter part. The hole in DI_Collector_mirror_block pass the metal end of the M3 screw onto the 'blind' plate of plastic and deforms that blind plate of plastic to push it inwards. It is this deformed plastic which grips the inner part (DI_Cnd_to_UC). This is to avoid the little screw end from creating indentations on DI_Cnd_to_UC if it were applied directly and so help allow fine adjustment in alignment of the Köhler system. I haven't done the Köhler illuminator video tutorial yet so you could not have known this. Thanks for considering the project. Please note that I have set up a Twitter feed @Paul_Tadrous - where you will see some snippets and news items about PUMA. If you have a Twitter account, please consider re-tweeting some of my tweets to help reach more people. I welcome input from the community.
